--
-- PostgreSQL database dump
--
-- Dumped from database version 17.11 (Homebrew)
-- Dumped by pg_dump version 17.11 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: support_teams; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.support_teams (
    id bigint NOT NULL,
    description character varying(255) NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: support_teams_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.support_teams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.support_teams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ticket_comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ticket_comments (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    author_id bigint NOT NULL,
    ticket_id bigint NOT NULL
);


--
-- Name: ticket_comments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ticket_comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ticket_comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ticket_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ticket_history (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    new_value character varying(255),
    old_value character varying(255),
    changed_by bigint,
    ticket_id bigint NOT NULL
);


--
-- Name: ticket_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ticket_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ticket_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tickets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tickets (
    id bigint NOT NULL,
    ai_classification_status character varying(255),
    ai_confidence double precision,
    category character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text NOT NULL,
    priority character varying(255) NOT NULL,
    resolved_at timestamp(6) without time zone,
    sla_breached boolean NOT NULL,
    sla_deadline timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    assigned_agent_id bigint,
    customer_id bigint NOT NULL,
    support_team_id bigint,
    CONSTRAINT tickets_category_check CHECK (((category)::text = ANY ((ARRAY['ACCOUNT'::character varying, 'PAYMENT'::character varying, 'TECHNICAL'::character varying, 'DELIVERY'::character varying, 'REFUND'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT tickets_priority_check CHECK (((priority)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying, 'CRITICAL'::character varying])::text[]))),
    CONSTRAINT tickets_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'IN_PROGRESS'::character varying, 'WAITING_FOR_CUSTOMER'::character varying, 'RESOLVED'::character varying, 'CLOSED'::character varying])::text[])))
);


--
-- Name: tickets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tickets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tickets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255),
    role character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    support_team_id bigint,
    auth_provider character varying(255) DEFAULT 'LOCAL'::character varying NOT NULL,
    verification_token_expiry timestamp(6) without time zone,
    verification_token_hash character varying(64),
    email_verified boolean DEFAULT true NOT NULL,
    password_reset_token_expiry timestamp(6) without time zone,
    password_reset_token_hash character varying(64),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'AGENT'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: support_teams support_teams_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.support_teams
    ADD CONSTRAINT support_teams_pkey PRIMARY KEY (id);


--
-- Name: ticket_comments ticket_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ticket_comments
    ADD CONSTRAINT ticket_comments_pkey PRIMARY KEY (id);


--
-- Name: ticket_history ticket_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ticket_history
    ADD CONSTRAINT ticket_history_pkey PRIMARY KEY (id);


--
-- Name: tickets tickets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: support_teams ukbpdar3jeseetov21c1f9577mw; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.support_teams
    ADD CONSTRAINT ukbpdar3jeseetov21c1f9577mw UNIQUE (name);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users fk_users_support_team; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk_users_support_team FOREIGN KEY (support_team_id) REFERENCES public.support_teams(id);


--
-- Name: users fkbqky7k4028td72sghu09y0bw2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkbqky7k4028td72sghu09y0bw2 FOREIGN KEY (support_team_id) REFERENCES public.support_teams(id);


--
-- Name: tickets fkcj1as67j5097xremctap9h9fb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT fkcj1as67j5097xremctap9h9fb FOREIGN KEY (support_team_id) REFERENCES public.support_teams(id);


--
-- Name: tickets fkcl6she6ic7de97o1ryli2g95i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT fkcl6she6ic7de97o1ryli2g95i FOREIGN KEY (customer_id) REFERENCES public.users(id);


--
-- Name: tickets fkd52vyeeadu7t2amt7bq1txg4e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT fkd52vyeeadu7t2amt7bq1txg4e FOREIGN KEY (assigned_agent_id) REFERENCES public.users(id);


--
-- Name: ticket_comments fkdoce3fj1osdn71h25dhfs160v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ticket_comments
    ADD CONSTRAINT fkdoce3fj1osdn71h25dhfs160v FOREIGN KEY (ticket_id) REFERENCES public.tickets(id);


--
-- Name: ticket_history fkealiso7ie7nqm5rgtjk604am4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ticket_history
    ADD CONSTRAINT fkealiso7ie7nqm5rgtjk604am4 FOREIGN KEY (changed_by) REFERENCES public.users(id);


--
-- Name: ticket_history fkkkhg6aquudxfcbofalx8rtc6v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ticket_history
    ADD CONSTRAINT fkkkhg6aquudxfcbofalx8rtc6v FOREIGN KEY (ticket_id) REFERENCES public.tickets(id);


--
-- Name: ticket_comments fkos0lnd4l167jhmpw7tqn2d5el; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ticket_comments
    ADD CONSTRAINT fkos0lnd4l167jhmpw7tqn2d5el FOREIGN KEY (author_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--



